[package]
name = "practice"
version = "0.1.0"
edition = "2021"
description = "PRobabilistic Research and Analysis of C(RN|TMC) (and VAS) Tool Integration for Checking and Evaluation"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
evalexpr = "12.0.2"
prusti-contracts = "0.2.0"
# serde = { version = "1.0.215", features = ["derive"] }
